#ifndef __PLE_CONFIG_H__
#define __PLE_CONFIG_H__

/* ple_config.h. Generated by configure */

/*
  This file is part of the Parallel Location and Exchange library,
  intended to provide mesh or particle-based code coupling services.

  Copyright (C) 2005-2013  EDF

  This library is free software; you can redistribute it and/or
  modify it under the terms of the GNU Lesser General Public
  License as published by the Free Software Foundation; either
  version 2.1 of the License, or (at your option) any later version.

  This library is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public
  License along with this library; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*/

/* Complete version number */
#define PLE_VERSION "1.0.4"

/* Major version number */
#define PLE_MAJOR_VERSION 1

/* Minor version number */
#define PLE_MINOR_VERSION 0

/* Release version number */
#define PLE_RELEASE_VERSION 4

/* The size of a 'void *', as computed by sizeof. */
#define PLE_SIZEOF_VOID_P 8

/* The size of a 'short', as computed by sizeof. */
#define PLE_SIZEOF_SHORT 2

/* The size of a 'int', as computed by sizeof. */
#define PLE_SIZEOF_INT 4

/* The size of a 'long', as computed by sizeof. */
#define PLE_SIZEOF_LONG 8

/* The size of a 'long long', as computed by sizeof. */
#define PLE_SIZEOF_LONG_LONG 8

/* The size of a 'float', as computed by sizeof. */
#define PLE_SIZEOF_FLOAT 4

/* The size of a 'double', as computed by sizeof. */
#define PLE_SIZEOF_DOUBLE 8

/* PLE library configured with MPI support ? */
#define PLE_HAVE_MPI 1

#endif /* __PLE_CONFIG_H__ */
