include ../Makefile.in 


all:
	@echo
	#====================================================# 
	@echo "--> make [doxygen]"
	#====================================================#
	@echo 


doxygen:
	doxygen Doxyfile


clean:
	rm -rf  html  *~   
 
