# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: gagiuntoli/fermi:latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Check syntax
      run: |
        files=$(find src -name '*.cc' -o -name '*.h')
        issues=$(clang-format -style=file -output-replacements-xml $files | grep -c '<replacement ' || true)
        if [ $issues -gt 0 ]; then
          echo "Found formatting issues. Exiting."
          clang-format --dry-run $files
          exit 1
        fi
        echo "No syntax issues."

    - name: Configure CMake Debug
      run: cmake -B build-debug -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=g++

    - name: Build Debug
      run: cmake --build build-debug --parallel 4

    - name: Test Debug
      run: ctest --test-dir build-debug --output-on-failure

    - name: Configure CMake Release
      run: cmake -B build-release -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++

    - name: Build Release
      run: cmake --build build-release --parallel 4

    - name: Test Release
      run: ctest --test-dir build-release --output-on-failure
